### ISSUE TITLE
No current release compatible with latest OpenCL API Headers

### ISSUE THREAD

**Issue by paulmenzel** [OCL-dev/ocl-icd#21]
The latest ocl-icd release 2.3.0 from March 2021 fails to built with the latest [OpenCL API Headers release v2021.06.30](https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2021.06.30). As the [fix is in the master branch](https://github.com/OCL-dev/ocl-icd/commit/aed1832c81c0971ea001e12d41e04df834257f94), it’d be great, if you cut a new release.

**Comment by Kerilk** [comment]
Will do today. In the meantime, using `--enable-official-khronos-headers` should get around the issue and force the use of the included Khronos headers.

**Comment by paulmenzel** [comment]
Thank you for releasing https://github.com/OCL-dev/ocl-icd/releases/tag/v2.3.1.

**Comment by Kerilk** [comment]
You're welcome, thanks for reporting the issue.
