### ISSUE TITLE
missing configure script

### ISSUE THREAD

**Issue by mualloc** [OCL-dev/ocl-icd#5]
Hello,
There is no configure script although it is the first step of Basic Installation. How can I produce configure script to start building this package?

**Comment by vdanjean** [comment]
Hi,
Sorry, I did not see your message before.
As for all GNU AutoTool projects, the INSTALL file talks about build steps when using the released tarball (where the configure script is already generated).
If you start from source (git), just run the short ./bootstrap script before (but you will need all the GNU AutoTool programs to be installed). It will generate the missing parts.

  Regards,
    Vincent
