### ISSUE TITLE
Request: Environment variable to force loading a specific .icd

### ISSUE THREAD

**Issue by jamespharvey20** [OCL-dev/ocl-icd#6]
This is either a feature request, or a request to add documentation explaining how to use the feature if it already exists.  I've looked and asked others, and don't think there's a way to do this yet.

I'd like for there to be a way to have multiple OpenCL runtimes installed, and designate per application which to use.  (That is, if the application itself doesn't doing so within in.)

With [Vulkan Loader](https://github.com/KhronosGroup/Vulkan-Loader) installed, if the environment variable `VK_ICD_FILENAMES` is set when starting an application, the loader will force loading the specific Vulkan runtime given.  i.e. `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_ic64.json <someApp>` will force `amd_ic64.json` to be used, regardless of whether `someApp` has the ability to choose a specific Vulkan runtime.

With root access, there's some ways to do this, but it would be a lot nicer with an overriding varaiable.

`clinfo` and programs using OpenCL only see entries in `/etc/OpenCL/vendors/` if they end in `.icd`, so it's possible to rename all but one entry `.icd.disabled`.

I really hate the idea of renaming package-owned files though.  And, I don't know if there's any situations where this wouldn't work.

Also, `chmod 000` on all but 1 works as well.  Perhaps that's a little bit better than renaming a package-owned file.  I checked, and Arch's package manager (pacman) doesn't error when upgrading when there's "000" permissions on something it's overwriting (well, I was technically testing reinstalling) the package.  It of course does set the permissions back to their default.

I'd suggest naming the environment variable: `CL_ICD_FILENAMES`.

**Comment by jamespharvey20** [comment]
Sorry, I see with asciidoc, a2x, and xmlto installed, it properly builds the manpage and installs it.

I'll let the Arch maintainer know.

**Comment by vdanjean** [comment]
Hi,
A few additional comments:
- OCL_ICD_VENDORS is very flexible, but this is a specificity of this OpenCL ICD Loader (OCL_ICD_VENDORS is not part of the standard, and also not used by other implementations)
- about bootstrap and the tarball: bootstrap is not required when the tarball come from the autotools (ie after a 'make dist' or 'make distcheck'). If the tarball comes from the Git repo, it is as if this is a git repo, so bootstrap is required.
- patch are welcome (including about documentation). Do not hesitate.

  Regards,
    Vincent
