### ISSUE TITLE
ocl-icd-2.2.12 build fails with undefined reference to `dump_vendor_icd

### ISSUE THREAD

**Issue by juanitotc** [OCL-dev/ocl-icd#8]
Building ocl-icd-2.2.12 with gcc-8.2.0 linking fails with:

libtool: compile:  gcc -flto -fuse-linker-plugin -mtune=generic -Os -pipe -DHAVE_CONFIG_H -I. -Wall -I/usr/src/ocl-icd-2.2.12/khronos-headers -Wno-deprecated-declarations -DETC_OPENCL_VENDORS=\"/etc/OpenCL/vendors\" -MT libOpenCL_la-ocl_icd_loader_gen.lo -MD -MP -MF .deps/libOpenCL_la-ocl_icd_loader_gen.Tpo -c ocl_icd_loader_gen.c  -fPIC -DPIC -o .libs/libOpenCL_la-ocl_icd_loader_gen.o
mv -f .deps/libOpenCL_la-ocl_icd_loader_gen.Tpo .deps/libOpenCL_la-ocl_icd_loader_gen.Plo
/bin/sh ./libtool  --tag=CC   --mode=link gcc -flto -fuse-linker-plugin -mtune=generic -Os -pipe -Wno-deprecated-declarations   -DETC_OPENCL_VENDORS=\"/etc/OpenCL/vendors\"  -version-info 1:0:0  -Wl,--version-script,ocl_icd_loader_gen.map  -o libOpenCL.la -rpath /usr/local/lib libOpenCL_la-ocl_icd_loader.lo libOpenCL_la-ocl_icd_loader_gen.lo  -ldl 
libtool: link: gcc -flto -fuse-linker-plugin -mtune=generic -Os -pipe -shared  -fPIC -DPIC  .libs/libOpenCL_la-ocl_icd_loader.o .libs/libOpenCL_la-ocl_icd_loader_gen.o   -ldl  -flto -fuse-linker-plugin -mtune=generic -Os -Wl,--version-script -Wl,ocl_icd_loader_gen.map   -Wl,-soname -Wl,libOpenCL.so.1 -o .libs/libOpenCL.so.1.0.0
/tmp/ccSz86nS.ltrans0.ltrans.o: In function `_find_and_check_platforms':
<artificial>:(.text+0x9069): undefined reference to `dump_vendor_icd'
<artificial>:(.text+0xed3c): undefined reference to `dump_vendor_icd'
/usr/local/bin/ld: .libs/libOpenCL.so.1.0.0: hidden symbol `dump_vendor_icd' isn't defined
/usr/local/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:700: libOpenCL.la] Error 1
make[2]: Leaving directory '/usr/src/ocl-icd-2.2.12'
make[1]: *** [Makefile:994: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/ocl-icd-2.2.12'
make: *** [Makefile:572: all] Error 2

**Comment by juanitotc** [comment]
Ah - it's -Os that it doesn't like, it fails with both gcc-7.2.0 and gcc-8.2.0.

Using -O2, things work as expected.

**Comment by Kerilk** [comment]
Thanks for reporting this.
